# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-15 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'omds_hostalias',
            },
        ),
        migrations.CreateModel(
            name='KeyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typed', models.CharField(max_length=32)),
                ('envtype', models.CharField(max_length=32)),
                ('projectName', models.CharField(max_length=128)),
                ('serverName', models.CharField(max_length=32)),
                ('vhosts', models.CharField(max_length=128)),
                ('keyname', models.CharField(max_length=128)),
                ('confText', models.TextField()),
            ],
            options={
                'db_table': 'omds_keylist',
            },
        ),
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servearip', models.CharField(max_length=32)),
                ('keylist', models.ManyToManyField(through='confmanager.HostAlias', to='confmanager.KeyList')),
            ],
            options={
                'db_table': 'omds_servers',
            },
        ),
        migrations.AddField(
            model_name='hostalias',
            name='kid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confmanager.KeyList'),
        ),
        migrations.AddField(
            model_name='hostalias',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confmanager.Servers'),
        ),
    ]
