# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-11 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projectList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typed', models.CharField(max_length=50)),
                ('envtype', models.CharField(max_length=50)),
                ('projectName', models.CharField(max_length=200)),
                ('serverName', models.CharField(max_length=100)),
                ('vhosts', models.CharField(max_length=100)),
                ('keyname', models.CharField(max_length=100)),
                ('confText', models.TextField()),
            ],
            options={
                'db_table': 'omds_projectList',
            },
        ),
    ]
